### ISSUE TITLE
Using MIT license in fork

### ISSUE THREAD

**Issue by balasub** [Microsoft/formula#10]
The current license for Formula is the Microsoft Public License [0]. We maintain a fork [1] in which we would like to use an MIT license. If we remove all gplex and gppg dependencies (which are there solely for legacy testing), can we use an MIT license in our forked repo?

It seems that Z3 went through a similar change (its original license when it was released on GitHub in 2012 was a "Microsoft Research License Agreement Non-Commercial Use Only," and in 2016 it moved to an MIT license [2]).

[0] https://github.com/microsoft/formula/blob/master/Doc/Licenses/license_formula.txt
[1] https://github.com/VUISIS/formula
[2] https://github.com/Z3Prover/z3/commits/master/LICENSE.txt

**Comment by lovettchris** [comment]
like this https://github.com/microsoft/formula/pull/11 ?

**Comment by balasub** [comment]
Exactly! Thanks.

One minor note: the Z3 license mentions Coyote rather than Z3: https://github.com/microsoft/formula/blob/master/Doc/Licenses/license_z3.txt#L3

**Comment by lovettchris** [comment]
woops good catch, thanks, fixed in pull request #12.
